# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:53:45+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Header, Path
from pydantic import constr

from models import (
    OBErrorResponse1,
    OBFundsConfirmation1,
    OBFundsConfirmationConsent1,
    OBFundsConfirmationConsentResponse1,
    OBFundsConfirmationResponse1,
)

app = MCPProxy(
    contact={'email': 'ServiceDesk@openbanking.org.uk', 'name': 'Service Desk'},
    description='Swagger for Confirmation of Funds API Specification',
    license={
        'name': 'open-licence',
        'url': 'https://www.openbanking.org.uk/open-licence',
    },
    termsOfService='https://www.openbanking.org.uk/terms',
    title='Confirmation of Funds API Specification',
    version='3.1.7',
    servers=[
        {'url': 'https://openbanking.org.uk'},
        {'url': '/open-banking/v3.1/cbpii'},
    ],
)


@app.post(
    '/funds-confirmation-consents',
    tags=['funds_confirmation_management', 'funds_confirmation_processing'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_funds_confirmation_consents(
    x_fapi_auth_date: Optional[
        constr(
            pattern=r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} (GMT|UTC)$'
        )
    ] = Header(None, alias='x-fapi-auth-date'),
    x_fapi_customer_ip_address: Optional[str] = Header(
        None, alias='x-fapi-customer-ip-address'
    ),
    x_fapi_interaction_id: Optional[str] = Header(None, alias='x-fapi-interaction-id'),
    authorization: str = Header(..., alias='Authorization'),
    x_customer_user_agent: Optional[str] = Header(None, alias='x-customer-user-agent'),
    body: OBFundsConfirmationConsent1 = ...,
):
    """
    Create Funds Confirmation Consent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/funds-confirmation-consents/{ConsentId}',
    tags=['funds_confirmation_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def delete_funds_confirmation_consents_consent_id(
    consent_id: str = Path(..., alias='ConsentId'),
    x_fapi_auth_date: Optional[
        constr(
            pattern=r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} (GMT|UTC)$'
        )
    ] = Header(None, alias='x-fapi-auth-date'),
    x_fapi_customer_ip_address: Optional[str] = Header(
        None, alias='x-fapi-customer-ip-address'
    ),
    x_fapi_interaction_id: Optional[str] = Header(None, alias='x-fapi-interaction-id'),
    authorization: str = Header(..., alias='Authorization'),
    x_customer_user_agent: Optional[str] = Header(None, alias='x-customer-user-agent'),
):
    """
    Delete Funds Confirmation Consent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/funds-confirmation-consents/{ConsentId}',
    tags=['funds_confirmation_management', 'funds_confirmation_processing'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def get_funds_confirmation_consents_consent_id(
    consent_id: str = Path(..., alias='ConsentId'),
    x_fapi_auth_date: Optional[
        constr(
            pattern=r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} (GMT|UTC)$'
        )
    ] = Header(None, alias='x-fapi-auth-date'),
    x_fapi_customer_ip_address: Optional[str] = Header(
        None, alias='x-fapi-customer-ip-address'
    ),
    x_fapi_interaction_id: Optional[str] = Header(None, alias='x-fapi-interaction-id'),
    authorization: str = Header(..., alias='Authorization'),
    x_customer_user_agent: Optional[str] = Header(None, alias='x-customer-user-agent'),
):
    """
    Get Funds Confirmation Consent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/funds-confirmations',
    tags=['funds_confirmation_management', 'funds_confirmation_processing'],
    security=[
        UnsuportedSecurityStub(name="None"),
    ],
)
def create_funds_confirmations(
    x_fapi_auth_date: Optional[
        constr(
            pattern=r'^(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4} \d{2}:\d{2}:\d{2} (GMT|UTC)$'
        )
    ] = Header(None, alias='x-fapi-auth-date'),
    x_fapi_customer_ip_address: Optional[str] = Header(
        None, alias='x-fapi-customer-ip-address'
    ),
    x_fapi_interaction_id: Optional[str] = Header(None, alias='x-fapi-interaction-id'),
    authorization: str = Header(..., alias='Authorization'),
    x_customer_user_agent: Optional[str] = Header(None, alias='x-customer-user-agent'),
    body: OBFundsConfirmation1 = ...,
):
    """
    Create Funds Confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
