# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:53:45+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, constr


class ISODateTime(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )


class Links(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    First: Optional[AnyUrl] = None
    Last: Optional[AnyUrl] = None
    Next: Optional[AnyUrl] = None
    Prev: Optional[AnyUrl] = None
    Self: AnyUrl


class Meta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    FirstAvailableDateTime: Optional[ISODateTime] = None
    LastAvailableDateTime: Optional[ISODateTime] = None
    TotalPages: Optional[int] = None


class OBError1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ErrorCode: str = Field(
        ..., description='Low level textual error code, e.g., UK.OBIE.Field.Missing'
    )
    Message: constr(min_length=1, max_length=500) = Field(
        ...,
        description="A description of the error that occurred. e.g., 'A mandatory field isn't supplied' or 'RequestedExecutionDateTime must be in future'\nOBIE doesn't standardise this field",
    )
    Path: Optional[constr(min_length=1, max_length=500)] = Field(
        None,
        description='Recommended but optional reference to the JSON Path of the field with error, e.g., Data.Initiation.InstructedAmount.Currency',
    )
    Url: Optional[str] = Field(
        None,
        description='URL to help remediate the problem, or provide more information, or to API Reference, or help etc',
    )


class OBErrorResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Code: constr(min_length=1, max_length=40) = Field(
        ..., description='High level textual error code, to help categorize the errors.'
    )
    Errors: List[OBError1] = Field(..., min_length=1)
    Id: Optional[constr(min_length=1, max_length=40)] = Field(
        None,
        description='A unique reference for the error instance, for audit purposes, in case of unknown/unclassified errors.',
    )
    Message: constr(min_length=1, max_length=500) = Field(
        ...,
        description="Brief Error message, e.g., 'There is something wrong with the request parameters provided'",
    )


class InstructedAmount(BaseModel):
    Amount: constr(pattern=r'^\d{1,13}$|^\d{1,13}\.\d{1,5}$') = Field(
        ...,
        description='A number of monetary units specified in an active currency where the unit of currency is explicit and compliant with ISO 4217.',
    )
    Currency: constr(pattern=r'^[A-Z]{3,3}$') = Field(
        ...,
        description='A code allocated to a currency by a Maintenance Agency under an international identification scheme, as described in the latest edition of the international standard ISO 4217 "Codes for the representation of currencies and funds".',
    )


class Data(BaseModel):
    ConsentId: constr(min_length=1, max_length=128) = Field(
        ...,
        description='Unique identification as assigned by the ASPSP to uniquely identify the funds confirmation consent resource.',
    )
    InstructedAmount_1: InstructedAmount = Field(
        ...,
        alias='InstructedAmount',
        description='Amount of money to be confirmed as available funds in the debtor account. Contains an Amount and a Currency.',
    )
    Reference: constr(min_length=1, max_length=35) = Field(
        ...,
        description='Unique reference, as assigned by the CBPII, to unambiguously refer to the request related to the payment transaction.',
    )


class OBFundsConfirmation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data_1: Data = Field(..., alias='Data')


class DebtorAccount(BaseModel):
    Identification: constr(min_length=1, max_length=256) = Field(
        ...,
        description='Identification assigned by an institution to identify an account. This identification is known by the account owner.',
    )
    Name: Optional[constr(min_length=1, max_length=350)] = Field(
        None,
        description='Name of the account, as assigned by the account servicing institution.\nUsage: The account name is the name or names of the account owner(s) represented at an account level. The account name is not the product name or the nickname of the account.',
    )
    SchemeName: str = Field(
        ...,
        description='Name of the identification scheme, in a coded form as published in an external list.',
    )
    SecondaryIdentification: Optional[constr(min_length=1, max_length=34)] = Field(
        None,
        description='This is secondary identification of the account, as assigned by the account servicing institution. \nThis can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination).',
    )


class Data1(BaseModel):
    DebtorAccount_1: DebtorAccount = Field(
        ...,
        alias='DebtorAccount',
        description='Unambiguous identification of the account of the debtor to which a confirmation of funds consent will be applied.',
    )
    ExpirationDateTime: Optional[datetime] = Field(
        None,
        description='Specified date and time the funds confirmation authorisation will expire.\n If this is not populated, the authorisation will be open ended.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )


class OBFundsConfirmationConsent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: Data1


class Status(Enum):
    Authorised = 'Authorised'
    AwaitingAuthorisation = 'AwaitingAuthorisation'
    Rejected = 'Rejected'
    Revoked = 'Revoked'


class Data2(BaseModel):
    ConsentId: constr(min_length=1, max_length=128) = Field(
        ...,
        description='Unique identification as assigned to identify the funds confirmation consent resource.',
    )
    CreationDateTime: datetime = Field(
        ...,
        description='Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )
    DebtorAccount_1: DebtorAccount = Field(
        ...,
        alias='DebtorAccount',
        description='Unambiguous identification of the account of the debtor to which a confirmation of funds consent will be applied.',
    )
    ExpirationDateTime: Optional[datetime] = Field(
        None,
        description='Specified date and time the funds confirmation authorisation will expire.\nIf this is not populated, the authorisation will be open ended.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )
    Status_1: Status = Field(
        ...,
        alias='Status',
        description='Specifies the status of consent resource in code form.',
    )
    StatusUpdateDateTime: datetime = Field(
        ...,
        description='Date and time at which the resource status was updated.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )


class OBFundsConfirmationConsentResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: Data2
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')


class Data3(BaseModel):
    ConsentId: constr(min_length=1, max_length=128) = Field(
        ...,
        description='Unique identification as assigned by the ASPSP to uniquely identify the funds confirmation consent resource.',
    )
    CreationDateTime: datetime = Field(
        ...,
        description='Date and time at which the resource was created.All dates in the JSON payloads are represented in ISO 8601 date-time format. \nAll date-time fields in responses must include the timezone. An example is below:\n2017-04-05T10:43:07+00:00',
    )
    FundsAvailable: bool = Field(
        ..., description='Flag to indicate the result of a confirmation of funds check.'
    )
    FundsConfirmationId: constr(min_length=1, max_length=40) = Field(
        ...,
        description='Unique identification as assigned by the ASPSP to uniquely identify the funds confirmation resource.',
    )
    InstructedAmount_1: InstructedAmount = Field(
        ...,
        alias='InstructedAmount',
        description='Amount of money to be confirmed as available funds in the debtor account. Contains an Amount and a Currency.',
    )
    Reference: constr(min_length=1, max_length=35) = Field(
        ...,
        description='Unique reference, as assigned by the CBPII, to unambiguously refer to the request related to the payment transaction.',
    )


class OBFundsConfirmationResponse1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    Data: Data3
    Links_1: Optional[Links] = Field(None, alias='Links')
    Meta_1: Optional[Meta] = Field(None, alias='Meta')
